# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jlegault/workspace/qdl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jlegault/workspace/qdl

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jlegault/workspace/qdl/CMakeFiles /home/jlegault/workspace/qdl//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jlegault/workspace/qdl/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named qdl

# Build rule for target.
qdl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qdl
.PHONY : qdl

# fast build rule for target.
qdl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qdl.dir/build.make CMakeFiles/qdl.dir/build
.PHONY : qdl/fast

firehose.o: firehose.c.o
.PHONY : firehose.o

# target to build an object file
firehose.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qdl.dir/build.make CMakeFiles/qdl.dir/firehose.c.o
.PHONY : firehose.c.o

firehose.i: firehose.c.i
.PHONY : firehose.i

# target to preprocess a source file
firehose.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qdl.dir/build.make CMakeFiles/qdl.dir/firehose.c.i
.PHONY : firehose.c.i

firehose.s: firehose.c.s
.PHONY : firehose.s

# target to generate assembly for a file
firehose.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qdl.dir/build.make CMakeFiles/qdl.dir/firehose.c.s
.PHONY : firehose.c.s

patch.o: patch.c.o
.PHONY : patch.o

# target to build an object file
patch.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qdl.dir/build.make CMakeFiles/qdl.dir/patch.c.o
.PHONY : patch.c.o

patch.i: patch.c.i
.PHONY : patch.i

# target to preprocess a source file
patch.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qdl.dir/build.make CMakeFiles/qdl.dir/patch.c.i
.PHONY : patch.c.i

patch.s: patch.c.s
.PHONY : patch.s

# target to generate assembly for a file
patch.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qdl.dir/build.make CMakeFiles/qdl.dir/patch.c.s
.PHONY : patch.c.s

program.o: program.c.o
.PHONY : program.o

# target to build an object file
program.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qdl.dir/build.make CMakeFiles/qdl.dir/program.c.o
.PHONY : program.c.o

program.i: program.c.i
.PHONY : program.i

# target to preprocess a source file
program.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qdl.dir/build.make CMakeFiles/qdl.dir/program.c.i
.PHONY : program.c.i

program.s: program.c.s
.PHONY : program.s

# target to generate assembly for a file
program.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qdl.dir/build.make CMakeFiles/qdl.dir/program.c.s
.PHONY : program.c.s

qdl.o: qdl.c.o
.PHONY : qdl.o

# target to build an object file
qdl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qdl.dir/build.make CMakeFiles/qdl.dir/qdl.c.o
.PHONY : qdl.c.o

qdl.i: qdl.c.i
.PHONY : qdl.i

# target to preprocess a source file
qdl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qdl.dir/build.make CMakeFiles/qdl.dir/qdl.c.i
.PHONY : qdl.c.i

qdl.s: qdl.c.s
.PHONY : qdl.s

# target to generate assembly for a file
qdl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qdl.dir/build.make CMakeFiles/qdl.dir/qdl.c.s
.PHONY : qdl.c.s

sahara.o: sahara.c.o
.PHONY : sahara.o

# target to build an object file
sahara.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qdl.dir/build.make CMakeFiles/qdl.dir/sahara.c.o
.PHONY : sahara.c.o

sahara.i: sahara.c.i
.PHONY : sahara.i

# target to preprocess a source file
sahara.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qdl.dir/build.make CMakeFiles/qdl.dir/sahara.c.i
.PHONY : sahara.c.i

sahara.s: sahara.c.s
.PHONY : sahara.s

# target to generate assembly for a file
sahara.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qdl.dir/build.make CMakeFiles/qdl.dir/sahara.c.s
.PHONY : sahara.c.s

ufs.o: ufs.c.o
.PHONY : ufs.o

# target to build an object file
ufs.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qdl.dir/build.make CMakeFiles/qdl.dir/ufs.c.o
.PHONY : ufs.c.o

ufs.i: ufs.c.i
.PHONY : ufs.i

# target to preprocess a source file
ufs.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qdl.dir/build.make CMakeFiles/qdl.dir/ufs.c.i
.PHONY : ufs.c.i

ufs.s: ufs.c.s
.PHONY : ufs.s

# target to generate assembly for a file
ufs.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qdl.dir/build.make CMakeFiles/qdl.dir/ufs.c.s
.PHONY : ufs.c.s

util.o: util.c.o
.PHONY : util.o

# target to build an object file
util.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qdl.dir/build.make CMakeFiles/qdl.dir/util.c.o
.PHONY : util.c.o

util.i: util.c.i
.PHONY : util.i

# target to preprocess a source file
util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qdl.dir/build.make CMakeFiles/qdl.dir/util.c.i
.PHONY : util.c.i

util.s: util.c.s
.PHONY : util.s

# target to generate assembly for a file
util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qdl.dir/build.make CMakeFiles/qdl.dir/util.c.s
.PHONY : util.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... qdl"
	@echo "... firehose.o"
	@echo "... firehose.i"
	@echo "... firehose.s"
	@echo "... patch.o"
	@echo "... patch.i"
	@echo "... patch.s"
	@echo "... program.o"
	@echo "... program.i"
	@echo "... program.s"
	@echo "... qdl.o"
	@echo "... qdl.i"
	@echo "... qdl.s"
	@echo "... sahara.o"
	@echo "... sahara.i"
	@echo "... sahara.s"
	@echo "... ufs.o"
	@echo "... ufs.i"
	@echo "... ufs.s"
	@echo "... util.o"
	@echo "... util.i"
	@echo "... util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

