name: Buildtest

on:
  pull_request:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04, ubuntu-22.04, ubuntu-20.04, macos-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libusb-1.0-0-dev

      - name: Dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install libxml2
          brew install libusb

      - name: Build
        run: make
