name: Checkpatch Review
on: [pull_request]
jobs:
  check-patch:
    name: checkpatch review
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - name: Run checkpatch review
      env:
        CHECKPATCH_BASE: ${{ github.event.pull_request.base.sha }}
        CHECKPATCH_HEAD: ${{ github.event.pull_request.head.sha }}
      run: ./scripts/checkpatch_wrapper.sh check-range
