name: Markdown Lint
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install mdl
      run: |
        sudo apt-get update
        sudo apt-get install -y markdownlint
    - name: Run markdown-lint
      run: ./scripts/markdownlint_wrapper.sh check
